import {
    defaultAccentColor,
    defaultAppBlack,
    defaultAppColor,
    defaultAppGreen,
    defaultButtonHeight,
} from "./const";
import {
    widthPercentageToDP as wp,
    heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const homeStyle: any = {
    homeScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
    },
};

export const fundWalletStyle: any = {
    fundWalletScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        firstSection: {
            paddingTop: hp(1.5),
            paddingBottom: hp(2),
            paddingLeft: wp(5),
            paddingRight: wp(5),
            infoText: {
                fontFamily: "BricolageLight",
                letterSpacing: 0.5,
                fontSize: 21,
                lineHeight: 35,
                color: defaultAppGreen,
            },
            bankDetails: {
                paddingTop: hp(4),
                paddingBottom: hp(4),
                paddingLeft: wp(2),
                paddingRight: wp(2),
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "flex-start",
                gap: 20,
                icon: {
                    width: 55,
                    height: 55,
                    borderRadius: 50,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    backgroundColor: defaultAccentColor,
                },
                textDiv: {
                    bankName: {
                        fontSize: 16,
                        textTransform: "uppercase",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.5,
                        color: "rgba(22,35,2,0.8)",
                        paddingBottom: 2,
                    },
                    accountNumber: {
                        fontSize: 35,
                        fontFamily: "SFBold",
                        letterSpacing: 0.8,
                        color: defaultAppGreen,
                        paddingTop: 2,
                    },
                },
            },
        },
        otherMethodSection: {
            paddingTop: hp(2),
            paddingBottom: hp(2),
            paddingLeft: wp(4.5),
            paddingRight: wp(4.5),
            titleText: {
                fontFamily: "BricolageLight",
                letterSpacing: 0.3,
                fontSize: 22,
                color: defaultAppGreen,
            },
            methodList: {
                flexDirection: "row",
                justifyContent: "space-between",
                paddingTop: hp(2),
                paddingBottom: hp(2),
                paddingLeft: wp(1),
                paddingRight: wp(1),
            },
        },
    },
};

export const qrCodeStyle: any = {
    qrCodeScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            titleText: {
                textAlign: "center",
                fontFamily: "BricolageLight",
                fontSize: 19,
                letterSpacing: 0.4,
                color: defaultAppGreen,
            },
            imageDiv: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                paddingTop: hp(2.7),
                paddingBottom: hp(2.5),
                image: {
                    width: wp(42),
                    height: hp(20),
                },
            },
            currencyValueContainer: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                gap: 45,
                paddingBottom: hp(2),
                currencyOne: {
                    fontFamily: "BricolageLight",
                    fontSize: 21,
                    letterSpacing: 0.4,
                    color: defaultAccentColor,
                },
                currencyTwo: {
                    fontFamily: "BricolageLight",
                    fontSize: 19,
                    letterSpacing: 0.4,
                    color: "#000000",
                },
            },
            infoContainer: {
                paddingLeft: wp(12),
                paddingRight: wp(12),
                paddingTop: hp(1.5),
                paddingBottom: hp(3.5),
                text: {
                    fontFamily: "BricolageLight",
                    fontSize: 17,
                    letterSpacing: 0.4,
                    textAlign: "center",
                    color: "rgba(22,35,2,0.8)",
                },
            },
            paymentDetailsContent: {
                paddingTop: hp(1.5),
                paddingBottom: wp(1.5),
                paddingLeft: wp(7),
                paddingRight: wp(7),
                titleText: {
                    fontFamily: "BricolageLight",
                    fontSize: 19,
                    letterSpacing: 0.4,
                    color: "rgba(22,35,2,0.7)",
                },
                addressContent: {
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "space-between",
                    paddingTop: hp(1.5),
                    paddingBottom: hp(1.5),
                    paddingLeft: wp(1),
                    paddingRight: wp(1),
                    borderRadius: 15,
                    text: {
                        color: defaultAppGreen,
                        fontFamily: "BricolageLight",
                        fontSize: 18,
                        letterSpacing: 1,
                    },
                    button: {
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "center",
                        backgroundColor: defaultAccentColor,
                        height: hp(3.4),
                        paddingLeft: wp(5),
                        paddingRight: wp(5),
                        paddingBottom: 2,
                        borderRadius: 7,
                        text: {
                            color: "#ffffff",
                            fontFamily: "BricolageLight",
                            fontSize: 15,
                            letterSpacing: 0.3,
                        },
                    },
                },
            },
            buttonsDiv: {
                paddingTop: hp(3.5),
                paddingBottom: hp(3.5),
                paddingLeft: wp(4.5),
                paddingRight: wp(4.5),
                firstButton: {
                    height: hp(6.1),
                    borderRadius: 9,
                    borderWidth: 1.5,
                    borderColor: "#DCDCEA",
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    marginTop: hp(1.2),
                    marginBottom: hp(1.2),
                    gap: 7,
                    text: {
                        fontFamily: "BricolageLight",
                        fontSize: 19,
                        letterSpacing: 0.5,
                        color: defaultAccentColor,
                    },
                },
                secondButton: {
                    height: hp(6.1),
                    borderRadius: 9,
                    borderWidth: 1.5,
                    gap: 7,
                    borderColor: defaultAccentColor,
                    backgroundColor: defaultAccentColor,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    marginTop: hp(1.2),
                    marginBottom: hp(1.2),
                    text: {
                        fontFamily: "BricolageLight",
                        fontSize: 19,
                        letterSpacing: 0.5,
                        color: "#ffffff",
                    },
                },
            },
        },
    },
};

export const requestPaymentStyle: any = {
    requestPaymentScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(2.5),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            inputDiv: {
                paddingTop: hp(1.7),
                paddingBottom: hp(1.7),
                label: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    paddingTop: hp(0.5),
                    paddingBottom: hp(0.5),
                    paddingLeft: wp(0.5),
                    paddingRight: wp(0.5),
                    fontSize: 17,
                    color: defaultAppGreen,
                },
                customInput: {
                    height: 60,
                    borderWidth: 1.3,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 13,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    fontSize: 18,
                },
                pressableField: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 10,
                    height: 61,
                    borderWidth: 1,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 10,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    paddingTop: hp(1),
                    paddingBottom: hp(1),
                    image: {
                        width: 42.4,
                        height: "100%",
                        borderRadius: 60,
                    },
                    text: {
                        color: "rgba(0,0,0,0.35)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                    activeText: {
                        color: "rgba(0,0,0,1)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                },
            },
            buttonDiv: {
                paddingTop: hp(2.5),
                paddingBottom: hp(1.5),
                button: {
                    height: 56,
                    borderRadius: 11,
                    flexDirection: "row",
                    justifyContent: "center",
                    alignItems: "center",
                    backgroundColor: defaultAccentColor,
                    text: {
                        color: "#ffffff",
                        fontSize: 20,
                        letterSpacing: 0.5,
                        fontFamily: "BricolageLight",
                    },
                },
            },
        },
    },
};

export const sendNairaStyle: any = {
    sendNairaScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            currentBalance: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                paddingTop: hp(0.5),
                paddingBottom: hp(0.5),
                text: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    textTransform: "uppercase",
                    fontSize: 16,
                    color: "rgba(0,0,0,0.8)",
                },
                amountText: {
                    color: "rgba(0,0,0,1)",
                    fontSize: 17,
                },
            },
            inputDiv: {
                paddingTop: hp(1.5),
                paddingBottom: hp(1.5),
                label: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    paddingTop: hp(0.5),
                    paddingBottom: hp(0.5),
                    paddingLeft: wp(0.5),
                    paddingRight: wp(0.5),
                    fontSize: 17,
                    color: defaultAppGreen,
                },
                customInput: {
                    height: 60,
                    borderWidth: 1.3,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 13,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    fontSize: 18,
                },
                pressableField: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 10,
                    height: 61,
                    borderWidth: 1,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 10,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    paddingTop: hp(1),
                    paddingBottom: hp(1),
                    image: {
                        width: 42.4,
                        height: "100%",
                        borderRadius: 60,
                    },
                    text: {
                        color: "rgba(0,0,0,0.35)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                    activeText: {
                        color: "rgba(0,0,0,1)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                },
            },
            buttonDiv: {
                paddingTop: hp(2.5),
                paddingBottom: hp(1.5),
                button: {
                    height: defaultButtonHeight,
                    borderRadius: 11,
                    flexDirection: "row",
                    justifyContent: "center",
                    alignItems: "center",
                    backgroundColor: defaultAccentColor,
                    text: {
                        color: "#ffffff",
                        fontSize: 18,
                        letterSpacing: 0.4,
                        fontFamily: "BricolageLight",
                        textTransform: "uppercase",
                    },
                },
            },
        },
    },
};

export const confirmTransferStyle: any = {
    confirmTransferScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            amountDetails: {
                paddingTop: hp(4),
                paddingBottom: hp(4),
                paddingLeft: wp(2),
                paddingRight: wp(2),
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "flex-start",
                gap: 20,
                icon: {
                    width: 50,
                    height: 50,
                    borderRadius: 50,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    backgroundColor: "rgba(127,192,20,0.2)",
                },
                textDiv: {
                    infoText: {
                        fontSize: 19,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.5,
                        color: "rgba(22,35,2,0.8)",
                        paddingBottom: 1,
                    },
                    amountText: {
                        fontSize: 35,
                        fontFamily: "SFBold",
                        letterSpacing: 0.1,
                        color: defaultAppGreen,
                        paddingTop: 1,
                    },
                },
            },
            transactionDetails: {
                paddingTop: hp(1),
                paddingBottom: hp(1),
                paddingLeft: wp(4),
                paddingRight: wp(4),
                singleInfoContent: {
                    paddingTop: hp(1.2),
                    paddingBottom: hp(1.2),
                    titleText: {
                        fontSize: 14.5,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.6,
                        color: "rgba(22,35,0,0.85)",
                        paddingTop: 2,
                        paddingBottom: 2,
                        textTransform: "uppercase",
                    },
                    bodyText: {
                        fontSize: 21,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        textTransform: "uppercase",
                        color: defaultAppGreen,
                        paddingTop: 5,
                        paddingBottom: 5,
                    },
                    flexView: {
                        paddingTop: 2,
                        paddingBottom: 2,
                        flexDirection: "row",
                        justifyContent: "space-between",
                        alignItems: "center",
                        text: {
                            fontSize: 21,
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.4,
                            textTransform: "uppercase",
                            color: "#000000",
                        },
                        image: {
                            width: 40,
                            height: 40,
                            borderRadius: 60,
                        },
                    },
                },
            },
            buttonDiv: {
                flexDirection: "row",
                paddingTop: hp(5),
                paddingBottom: hp(5),
                paddingLeft: wp(1.5),
                paddingRight: wp(1.5),
                button: {
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    height: defaultButtonHeight,
                    backgroundColor: defaultAccentColor,
                    width: "100%",
                    borderRadius: 8,
                    text: {
                        fontSize: 18,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        textTransform: "uppercase",
                        color: "#ffffff",
                    },
                },
            },
        },
    },
};
