import {
    defaultAccentColor,
    defaultAppBlack,
    defaultAppColor,
    defaultAppGreen,
    defaultButtonHeight,
    globalSidePadding,
} from "./const";
import {
    widthPercentageToDP as wp,
    heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const homeStyle: any = {
    homeScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
    },
};

export const settingStyle: any = {
    settingScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            linkList: {
                borderRadius: 20,
                backgroundColor: "rgba(0,0,0,0.01)",
                paddingTop: 5,
                paddingBottom: 5,
                paddingLeft: 15,
                paddingRight: 15,
                link: {
                    padding: 10,
                    paddingTop: 15,
                    paddingBottom: 15,
                    marginTop: 15,
                    marginBottom: 15,
                    flexDirection: "row",
                    justifyContent: "space-between",
                    alignItems: "center",
                    text: {
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.3,
                        fontSize: 19,
                    },
                    button: {},
                },
            },
            logoutContainer: {
                paddingTop: 50,
                paddingBottom: 0,
                paddingLeft: 5,
                paddingRight: 5,
                button: {
                    height: 62,
                    borderColor: "rgba(255, 201, 201, 1)",
                    borderWidth: 1,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "space-between",
                    paddingLeft: 15,
                    paddingRight: 15,
                    borderRadius: 8,
                    text: {
                        color: "rgba(255, 31, 31, 1)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                    icon: {},
                },
            },
        },
    },
};

export const fundWalletStyle: any = {
    fundWalletScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        firstSection: {
            paddingTop: hp(1.5),
            paddingBottom: hp(2),
            paddingLeft: wp(5),
            paddingRight: wp(5),
            infoText: {
                fontFamily: "BricolageLight",
                letterSpacing: 0.3,
                fontSize: 20,
                lineHeight: 35,
                color: "#000000",
            },
            bankDetails: {
                paddingTop: hp(4),
                paddingBottom: hp(4),
                paddingLeft: wp(2),
                paddingRight: wp(2),
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "flex-start",
                gap: 20,
                icon: {
                    width: 55,
                    height: 55,
                    borderRadius: 50,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    backgroundColor: "#000000",
                },
                textDiv: {
                    bankName: {
                        fontSize: 16,
                        textTransform: "uppercase",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.5,
                        color: "rgba(22,35,2,0.8)",
                        paddingBottom: 2,
                    },
                    accountNumber: {
                        fontSize: 35,
                        fontFamily: "SFBold",
                        letterSpacing: 0.8,
                        color: defaultAppGreen,
                        paddingTop: 2,
                    },
                },
            },
        },
        otherMethodSection: {
            paddingTop: hp(2),
            paddingBottom: hp(2),
            paddingLeft: wp(4.5),
            paddingRight: wp(4.5),
            titleText: {
                fontFamily: "BricolageLight",
                letterSpacing: 0.3,
                fontSize: 22,
                color: defaultAppGreen,
            },
            methodList: {
                flexDirection: "row",
                justifyContent: "space-between",
                paddingTop: hp(2),
                paddingBottom: hp(2),
                paddingLeft: wp(1),
                paddingRight: wp(1),
            },
        },
    },
};

export const qrCodeStyle: any = {
    qrCodeScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            titleText: {
                textAlign: "center",
                fontFamily: "BricolageLight",
                fontSize: 19,
                letterSpacing: 0.4,
                color: defaultAppGreen,
            },
            imageDiv: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                paddingTop: hp(2.7),
                paddingBottom: hp(2.5),
                image: {
                    width: wp(42),
                    height: hp(20),
                },
            },
            currencyValueContainer: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                gap: 45,
                paddingBottom: hp(2),
                currencyOne: {
                    fontFamily: "BricolageLight",
                    fontSize: 21,
                    letterSpacing: 0.4,
                    color: defaultAccentColor,
                },
                currencyTwo: {
                    fontFamily: "BricolageLight",
                    fontSize: 19,
                    letterSpacing: 0.4,
                    color: "#000000",
                },
            },
            infoContainer: {
                paddingLeft: wp(12),
                paddingRight: wp(12),
                paddingTop: hp(1.5),
                paddingBottom: hp(3.5),
                text: {
                    fontFamily: "BricolageLight",
                    fontSize: 17,
                    letterSpacing: 0.4,
                    textAlign: "center",
                    color: "rgba(22,35,2,0.8)",
                },
            },
            paymentDetailsContent: {
                paddingTop: hp(1.5),
                paddingBottom: wp(1.5),
                paddingLeft: wp(7),
                paddingRight: wp(7),
                titleText: {
                    fontFamily: "BricolageLight",
                    fontSize: 19,
                    letterSpacing: 0.4,
                    color: "rgba(22,35,2,0.7)",
                },
                addressContent: {
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "space-between",
                    paddingTop: hp(1.5),
                    paddingBottom: hp(1.5),
                    paddingLeft: wp(1),
                    paddingRight: wp(1),
                    borderRadius: 15,
                    text: {
                        color: defaultAppGreen,
                        fontFamily: "BricolageLight",
                        fontSize: 18,
                        letterSpacing: 1,
                    },
                    button: {
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "center",
                        backgroundColor: defaultAccentColor,
                        height: hp(3.4),
                        paddingLeft: wp(5),
                        paddingRight: wp(5),
                        paddingBottom: 2,
                        borderRadius: 7,
                        text: {
                            color: "#ffffff",
                            fontFamily: "BricolageLight",
                            fontSize: 15,
                            letterSpacing: 0.3,
                        },
                    },
                },
            },
            buttonsDiv: {
                paddingTop: hp(3.5),
                paddingBottom: hp(3.5),
                paddingLeft: wp(4.5),
                paddingRight: wp(4.5),
                firstButton: {
                    height: hp(6.1),
                    borderRadius: 9,
                    borderWidth: 1.5,
                    borderColor: "#DCDCEA",
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    marginTop: hp(1.2),
                    marginBottom: hp(1.2),
                    gap: 7,
                    text: {
                        fontFamily: "BricolageLight",
                        fontSize: 19,
                        letterSpacing: 0.5,
                        color: defaultAccentColor,
                    },
                },
                secondButton: {
                    height: hp(6.1),
                    borderRadius: 9,
                    borderWidth: 1.5,
                    gap: 7,
                    borderColor: defaultAccentColor,
                    backgroundColor: defaultAccentColor,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    marginTop: hp(1.2),
                    marginBottom: hp(1.2),
                    text: {
                        fontFamily: "BricolageLight",
                        fontSize: 19,
                        letterSpacing: 0.5,
                        color: "#ffffff",
                    },
                },
            },
        },
    },
};

export const requestPaymentStyle: any = {
    requestPaymentScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(2.5),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            inputDiv: {
                paddingTop: hp(1.7),
                paddingBottom: hp(1.7),
                label: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    paddingTop: hp(0.5),
                    paddingBottom: hp(0.5),
                    paddingLeft: wp(0.5),
                    paddingRight: wp(0.5),
                    fontSize: 17,
                    color: defaultAppGreen,
                },
                customInput: {
                    height: 60,
                    borderWidth: 1.3,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 13,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    fontSize: 18,
                },
                pressableField: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 10,
                    height: 61,
                    borderWidth: 1,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 10,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    paddingTop: hp(1),
                    paddingBottom: hp(1),
                    image: {
                        width: 42.4,
                        height: "100%",
                        borderRadius: 60,
                    },
                    text: {
                        color: "rgba(0,0,0,0.35)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                    activeText: {
                        color: "rgba(0,0,0,1)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                },
            },
            buttonDiv: {
                paddingTop: hp(2.5),
                paddingBottom: hp(1.5),
                button: {
                    height: 56,
                    borderRadius: 11,
                    flexDirection: "row",
                    justifyContent: "center",
                    alignItems: "center",
                    backgroundColor: defaultAccentColor,
                    text: {
                        color: "#ffffff",
                        fontSize: 20,
                        letterSpacing: 0.5,
                        fontFamily: "BricolageLight",
                    },
                },
            },
        },
    },
};

export const sendNairaStyle: any = {
    sendNairaScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: globalSidePadding,
            paddingRight: globalSidePadding,
            paddingBottom: hp(2),
            currentBalance: {
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                paddingTop: hp(0.5),
                paddingBottom: hp(0.5),
                text: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    textTransform: "uppercase",
                    fontSize: 16,
                    color: "rgba(0,0,0,0.8)",
                },
                amountText: {
                    color: "rgba(0,0,0,1)",
                    fontSize: 17,
                },
            },
            inputDiv: {
                paddingTop: hp(1.5),
                paddingBottom: hp(1.5),
                label: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    paddingTop: hp(0.5),
                    paddingBottom: hp(0.5),
                    paddingLeft: wp(0.5),
                    paddingRight: wp(0.5),
                    fontSize: 17,
                    color: defaultAppGreen,
                },
                customInput: {
                    height: 60,
                    borderWidth: 1.3,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 13,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    fontSize: 18,
                },
                pressableField: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 10,
                    height: 61,
                    borderWidth: 1,
                    borderColor: "rgba(0,0,0,0.1)",
                    borderRadius: 10,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    paddingTop: hp(1),
                    paddingBottom: hp(1),
                    image: {
                        width: 42.4,
                        height: "100%",
                        borderRadius: 60,
                    },
                    text: {
                        color: "rgba(0,0,0,0.35)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                    activeText: {
                        color: "rgba(0,0,0,1)",
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        fontSize: 18,
                    },
                },
            },
            buttonDiv: {
                paddingTop: hp(3.5),
                paddingBottom: hp(1.5),
                button: {
                    height: defaultButtonHeight,
                    borderRadius: 11,
                    flexDirection: "row",
                    justifyContent: "center",
                    alignItems: "center",
                    backgroundColor: defaultAccentColor,
                    text: {
                        color: "#ffffff",
                        fontSize: 18,
                        letterSpacing: 0.4,
                        fontFamily: "BricolageLight",
                        textTransform: "uppercase",
                    },
                },
            },
        },
    },
};

export const confirmTransferStyle: any = {
    confirmTransferScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            amountDetails: {
                paddingTop: hp(4),
                paddingBottom: hp(4),
                paddingLeft: wp(2),
                paddingRight: wp(2),
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "flex-start",
                gap: 20,
                icon: {
                    width: 50,
                    height: 50,
                    borderRadius: 50,
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    backgroundColor: "rgba(127,192,20,0.2)",
                },
                textDiv: {
                    infoText: {
                        fontSize: 19,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.5,
                        color: "rgba(22,35,2,0.8)",
                        paddingBottom: 1,
                    },
                    amountText: {
                        fontSize: 35,
                        fontFamily: "SFBold",
                        letterSpacing: 0.1,
                        color: defaultAppGreen,
                        paddingTop: 1,
                    },
                },
            },
            transactionDetails: {
                paddingTop: hp(1),
                paddingBottom: hp(1),
                paddingLeft: wp(4),
                paddingRight: wp(4),
                singleInfoContent: {
                    paddingTop: hp(1.4),
                    paddingBottom: hp(1.4),
                    titleText: {
                        fontSize: 14,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.6,
                        color: "rgba(22,35,0,0.85)",
                        paddingTop: 2,
                        paddingBottom: 2,
                        textTransform: "uppercase",
                    },
                    bodyText: {
                        fontSize: 21,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.4,
                        color: "#000000",
                        paddingTop: 5,
                        paddingBottom: 5,
                    },
                    flexView: {
                        paddingTop: 6,
                        paddingBottom: 6,
                        flexDirection: "row",
                        justifyContent: "space-between",
                        alignItems: "center",
                        text: {
                            fontSize: 21,
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.4,
                            color: "#000000",
                        },
                        tinyText: {
                            fontSize: 17,
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.4,
                            color: "rgba(0,0,0,0.8)",
                        },
                        image: {
                            width: 40,
                            height: 40,
                            borderRadius: 60,
                        },
                    },
                },
            },
            buttonDiv: {
                flexDirection: "row",
                paddingTop: hp(5),
                paddingBottom: hp(5),
                paddingLeft: wp(1.5),
                paddingRight: wp(1.5),
            },
        },
    },
};

export const confirmTransactionStyle: any = {
    confirmTransactionScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            keyboardDiv: {
                backgroundColor: "rgba(0,0,0,0.05)",
                height: "auto",
                width: "100%",
                paddingTop: hp(2.5),
                paddingBottom: 40,
                paddingLeft: wp(6),
                paddingRight: wp(6),
                borderTopLeftRadius: 30,
                borderTopRightRadius: 30,
                position: "absolute",
                bottom: 0,
                textDiv: {
                    amount: {
                        paddingTop: 16,
                        color: "#000000",
                        textAlign: "center",
                        height: 70,
                        fontSize: 37,
                        letterSpacing: 20,
                        fontFamily: "BricolageLight",
                        borderColor: "rgba(0,0,0,0.001)",
                        borderWidth: 1.5,
                        borderRadius: 35,
                    },
                    minimum: {
                        color: "rgba(0,0,0,0.8)",
                        paddingTop: 18,
                        paddingBottom: hp(1.8),
                        textAlign: "center",
                        fontFamily: "BricolageLight",
                        fontSize: 16,
                        letterSpacing: 0.5,
                    },
                },
                keyboard: {
                    paddingTop: hp(0.6),
                    paddingLeft: wp(4),
                    paddingRight: wp(4),
                    row: {
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "space-between",
                        keys: {
                            width: wp(20),
                            height: hp(10),
                            flexDirection: "row",
                            alignItems: "center",
                            justifyContent: "center",
                            text: {
                                color: "#000000",
                                fontFamily: "BricolageLight",
                                fontSize: 30,
                            },
                        },
                    },
                },
                sendButtonDiv: {
                    flexDirection: "row",
                    paddingTop: hp(2.3),
                    paddingLeft: wp(2.5),
                    paddingRight: wp(2.5),
                    button: {
                        width: "100%",
                        height: 58,
                        borderRadius: 30,
                        backgroundColor: defaultAccentColor,
                        flexDirection: "row",
                        justifyContent: "center",
                        alignItems: "center",
                        text: {
                            color: "#ffffff",
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.4,
                            fontSize: 19,
                        },
                    },
                },
            },
        },
    },
};

export const transactionSuccessStyle: any = {
    transactionSuccessScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        textBold: {
            fontFamily: "Bricolage",
            color: "rgba(0,0,0,1)",
            letterSpacing: -0.2,
        },
        screenContent: {
            paddingTop: hp(2.5),
            paddingLeft: globalSidePadding,
            paddingRight: globalSidePadding,
            paddingBottom: hp(2),
            imageDiv: {
                padding: 15,
                paddingTop: 20,
                flexDirection: "row",
                justifyContent: "center",
                image: {
                    width: 110,
                    height: 110,
                },
            },
            textDiv: {
                padding: 9.7,
                paddingTop: 20,
                paddingBottom: 15,
                text: {
                    paddingLeft: 40,
                    paddingRight: 40,
                    textAlign: "center",
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    color: "rgba(0,0,0,0.75)",
                    lineHeight: 25,
                    fontSize: 20,
                },
            },
            buttonDiv: {
                padding: 10,
                paddingTop: 60,
                paddingBottom: 50,
                button: {
                    height: 55,
                    borderRadius: 12,
                    backgroundColor: defaultAccentColor,
                    flexDirection: "row",
                    justifyContent: "center",
                    alignItems: "center",
                    text: {
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.3,
                        fontSize: 17,
                        color: "#ffffff",
                    },
                },
            },
        },
    },
};

export const billScreenStyle: any = {
    billScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            formContent: {
                paddingLeft: 10,
                paddingRight: 10,
                selectButtonDiv: {
                    flexDirection: "row",
                    justifyContent: "flex-end",
                    padding: 1,
                    button: {
                        padding: 4,
                        text: {
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.1,
                            fontSize: 14.5,
                            color: defaultAccentColor,
                        },
                    },
                },
                inputDiv: {
                    paddingTop: hp(1.7),
                    paddingBottom: hp(1.7),
                },
                label: {
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.5,
                    paddingTop: hp(0.5),
                    paddingBottom: hp(0.5),
                    paddingLeft: wp(0.3),
                    paddingRight: wp(0.3),
                    fontSize: 17,
                    color: "#000000",
                },
                input: {
                    height: 60,
                    borderWidth: 1.5,
                    borderColor: "rgba(0,0,0,0.15)",
                    borderRadius: 10,
                    paddingLeft: wp(3),
                    paddingRight: wp(3),
                    fontFamily: "BricolageLight",
                    letterSpacing: 0.4,
                    fontSize: 18,
                },
                selectNetworkDiv: {
                    padding: 5,
                    paddingTop: 20,
                    paddingBottom: 20,
                    flexDirection: "row",
                    justifyContent: "space-between",
                    singleNetwork: {
                        borderWidth: 2,
                        borderColor: "rgba(0,0,0,0.15)",
                        width: 55,
                        height: 55,
                        borderRadius: 60,
                        padding: 5,
                        image: {
                            borderRadius: 60,
                            width: "100%",
                            height: "100%",
                        },
                    },
                },
                amountSuggestionDiv: {
                    paddingTop: 10,
                    flex: 1,
                    flexDirection: "row",
                    flexWrap: "wrap",
                    gap: 10,
                    suggestion: {
                        marginTop: 5,
                        width: "30%",
                        padding: 10,
                        borderRadius: 10,
                        text: {
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.3,
                            fontSize: 16,
                        },
                    },
                },
                selectInputView: {
                    selectInput: {
                        height: 60,
                        borderWidth: 1.5,
                        borderColor: "rgba(0,0,0,0.15)",
                        borderRadius: 10,
                        paddingLeft: wp(3),
                        paddingRight: wp(3),
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "flex-start",
                        gap: 10,
                        image: {
                            width: 42,
                            height: 42,
                            borderRadius: 60,
                            borderWidth: 1.5,
                            borderColor: "rgba(0,0,0,0.15)",
                        },
                        text: {
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.3,
                            fontSize: 18,
                            color: "rgba(0,0,0,0.3)",
                        },
                    },
                },
                buttonDiv: {
                    paddingTop: hp(5),
                    paddingBottom: hp(2),
                    button: {
                        height: 56,
                        borderRadius: 10,
                        flexDirection: "row",
                        justifyContent: "center",
                        alignItems: "center",
                        backgroundColor: defaultAccentColor,
                        text: {
                            color: "#ffffff",
                            fontSize: 19,
                            letterSpacing: 0.4,
                            fontFamily: "BricolageLight",
                        },
                    },
                },
                tabDiv: {
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "space-between",
                    paddingTop: 10,
                    paddingBottom: 10,
                    button: {
                        width: "50%",
                        borderWidth: 1.5,
                        borderColor: "rgba(0,0,0,0.0)",
                        height: 58,
                        borderRadius: 8,
                        flexDirection: "row",
                        alignItems: "center",
                        justifyContent: "center",
                        text: {
                            color: defaultAccentColor,
                            fontSize: 17,
                            letterSpacing: 0.2,
                            fontFamily: "BricolageLight",
                        },
                    },
                },
            },
        },
    },
};

export const confirmAirtimePurchaseStyle: any = {
    confirmTransferScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        screenContent: {
            paddingTop: hp(1),
            paddingLeft: wp(4),
            paddingRight: wp(4),
            paddingBottom: hp(2),
            transactionDetails: {
                paddingTop: hp(1),
                paddingBottom: hp(1),
                paddingLeft: wp(4),
                paddingRight: wp(4),
                singleInfoContentBlock: {
                    paddingTop: hp(2.3),
                    paddingBottom: hp(2.3),
                    titleText: {
                        fontSize: 16,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.2,
                        color: "rgba(22,35,0,0.8)",
                        paddingBottom: 5,
                    },
                    bodyText: {
                        fontSize: 19,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.2,
                        color: "#000000",
                        paddingTop: 5,
                    },
                },
                singleInfoContent: {
                    paddingTop: hp(2.3),
                    paddingBottom: hp(2.3),
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "space-between",
                    titleText: {
                        fontSize: 16,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.2,
                        color: "rgba(22,35,0,0.8)",
                    },
                    bodyText: {
                        fontSize: 19,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.2,
                        color: "#000000",
                    },
                    flexView: {
                        paddingTop: 2,
                        paddingBottom: 2,
                        flexDirection: "row",
                        alignItems: "center",
                        gap: 10,
                        text: {
                            fontSize: 19,
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.2,
                            color: "#000000",
                        },
                        image: {
                            width: 30,
                            height: 30,
                            borderRadius: 60,
                        },
                    },
                },
            },
            buttonDiv: {
                flexDirection: "row",
                paddingTop: hp(5),
                paddingBottom: hp(5),
                paddingLeft: wp(1.5),
                paddingRight: wp(1.5),
                button: {
                    flexDirection: "row",
                    alignItems: "center",
                    justifyContent: "center",
                    height: defaultButtonHeight,
                    backgroundColor: defaultAccentColor,
                    width: "100%",
                    borderRadius: 10,
                    text: {
                        fontSize: 19,
                        fontFamily: "BricolageLight",
                        letterSpacing: 0.3,
                        color: "#ffffff",
                    },
                },
            },
        },
    },
};

export const historyStyle: any = {
    historyScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        paddingLeft: globalSidePadding,
        paddingRight: globalSidePadding,
        paddingBottom: 50,
        headerBar: {
            paddingTop: 35,
            paddingBottom: 20,
            flexDirection: "row",
            justifyContent: "space-between",
            width: "100%",
            alignItems: "center",
            titleText: {
                color: defaultAppBlack,
                fontSize: 22,
                fontFamily: "Bricolage",
                letterSpacing: 0.2,
            },
            filterButton: {
                borderColor: "rgba(0,0,0,0.25)",
                borderWidth: 1.5,
                padding: 12,
                borderRadius: 13,
                paddingLeft: 15,
                paddingRight: 15,
                flexDirection: "row",
                alignItems: "center",
                gap: 4,
                text: {
                    color: "#000000",
                    fontSize: 13,
                    fontFamily: "Bricolage",
                    letterSpacing: 0.5,
                },
            },
        },
        historyList: {
            width: "100%",
            backgroundColor: "rgba(0,0,0,0.1)",
            padding: 15,
            paddingTop: 10,
            paddingBottom: 40,
            borderRadius: 15,
            height: hp(76),
        },
    },
    transactionInvoiceScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        paddingLeft: globalSidePadding,
        paddingRight: globalSidePadding,
        invoiceIntro: {
            paddingTop: hp(2),
            imageDiv: {
                flexDirection: "row",
                justifyContent: "center",
                image: {
                    width: 100,
                    height: 99.5,
                },
            },
            captionText: {
                color: "rgba(0,0,0,0.8)",
                textAlign: "center",
                paddingTop: 17,
                paddingBottom: 17,
                fontSize: 17,
                fontFamily: "BricolageLight",
                letterSpacing: 0.2,
            },
            amountText: {
                color: "#000000",
                textAlign: "center",
                fontWeight: "500",
                fontFamily: "Bricolage",
                paddingBottom: hp(2),
                fontSize: 30,
                letterSpacing: 0.8,
            },
        },
        invoiceCardDiv: {
            paddingTop: hp(0.3),
            paddingLeft: 12,
            paddingRight: 12,
            paddingBottom: 27,
            width: "100%",
            invoiceCard: {
                marginTop: hp(1.3),
                marginBottom: hp(1.3),
                backgroundColor: "rgba(0,0,0,0.1)",
                paddingTop: hp(2.3),
                paddingBottom: hp(1.3),
                paddingLeft: wp(3),
                paddingRight: wp(3),
                borderRadius: 20,
                recipientContent: {
                    flexDirection: "row",
                    gap: wp(2.5),
                    paddingBottom: hp(1),
                    image: {
                        width: 50,
                        height: 51,
                        borderRadius: 60,
                    },
                    textDiv: {
                        paddingTop: hp(0.3),
                        titleText: {
                            color: "rgba(0,0,0,0.7)",
                            fontSize: 13,
                            fontFamily: "BricolageLight",
                            letterSpacing: 0.1,
                        },
                        subText: {
                            color: "#000000",
                            paddingTop: hp(0.3),
                            fontSize: 19,
                            fontFamily: "Bricolage",
                            letterSpacing: 0.3,
                        },
                    },
                },
                invoiceList: {
                    paddingLeft: 3,
                    paddingRight: 3,
                    list: {
                        paddingTop: 10,
                        paddingBottom: 10,
                        flexDirection: "row",
                        justifyContent: "space-between",
                        alignItems: "center",
                        title: {
                            color: "rgba(0,0,0,0.65)",
                            fontSize: 15,
                            fontFamily: "Bricolage",
                            letterSpacing: 0.4,
                        },
                        caption: {
                            color: "rgba(0,0,0,0.85)",
                            fontSize: 18,
                            fontFamily: "Bricolage",
                            letterSpacing: 0.4,
                        },
                        line: {
                            width: "100%",
                            flexDirection: "row",
                            justifyContent: "space-between",
                            text: {
                                color: "rgba(0,0,0,0.4)",
                            },
                            marginTop: hp(-0.5),
                            marginBottom: hp(-0.5),
                        },
                    },
                    shareButtonDiv: {
                        paddingTop: hp(2.5),
                        paddingBottom: hp(0.6),
                        flexDirection: "row",
                        width: "100%",
                        alignItems: "center",
                        justifyContent: "center",
                        button: {
                            flexDirection: "row",
                            width: "100%",
                            alignItems: "center",
                            justifyContent: "center",
                            backgroundColor: defaultAccentColor,
                            borderRadius: 10,
                            height: hp(5),
                            text: {
                                color: "#ffffff",
                                fontSize: 18,
                                fontFamily: "Bricolage",
                                letterSpacing: 0.5,
                            },
                        },
                    },
                },
            },
        },
    },
};

export const newsStyle: any = {
    newsScreen: {
        width: "100%",
        height: "100%",
        backgroundColor: defaultAppColor,
        flex: 1,
        alignItems: "center",
        paddingBottom: hp(10),
        headerNews: {
            paddingTop: hp(0.5),
            paddingBottom: hp(4),
            width: "100%",
            post: {
                width: "100%",
                paddingLeft: globalSidePadding,
                paddingRight: globalSidePadding,
                image: {
                    width: "100%",
                    height: 220,
                    borderRadius: 25,
                    borderWidth: 3,
                    borderColor: `${defaultAccentColor}33`,
                },
                title: {
                    color: "#000000",
                    paddingTop: hp(1.7),
                    paddingBottom: hp(1.2),
                    paddingLeft: wp(1),
                    paddingRight: wp(1),
                    fontFamily: "BricolageLight",
                    fontSize: 18,
                    letterSpacing: 0.2,
                },
                date: {
                    color: "rgba(0,0,0,0.7)",
                    fontFamily: "BricolageLight",
                    fontSize: 14,
                    letterSpacing: 0.2,
                    paddingLeft: wp(1),
                    paddingRight: wp(1),
                },
            },
        },
        newsList: {
            paddingLeft: globalSidePadding,
            paddingRight: globalSidePadding,
            paddingBottom: 70,
            width: "100%",
        },
    },
};
